add_newline = false
format = '''$character $directory
[\$](cyan) '''
command_timeout = 5000

[character]
format = '$symbol'
success_symbol = '[â—](bold green)'
error_symbol = '[â—](bold red)' 

[directory]
format = '[$read_only]($read_only_style)[$path]($style)'
style = 'cyan'
read_only = 'ğŸ”’ '
truncation_length = 5

[git_branch]
disabled = true
format = '[git:](cyan)[$branch(:$remote_branch)]($style) '
style = 'bold fg:230'

[git_status]
disabled = true
format = '$all_status$ahead_behind'
conflicted = '!'
ahead = 'a'
behind = 'b'
deleted = 'd'
modified = 'm'
staged = 's'
stashed = '$'
renamed = 'r'
up_to_date = 'u'
windows_starship = '/mnt/c/ProgramData/chocolatey/bin/starship.exe'
